<!DOCTYPE html>
<html lang="en">
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
   <title>DevNet - Framework</title>
   <!-- styles -->
   <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css">
</head>
<body>
   <header>
      <?= $this->renderPartial('layouts/navbar') ?>
   </header>
   <main>
      <?= $this->renderBody() ?>
   </main>
   <!-- scripts -->
   <script src="/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
   </body>
</html>