<?= $this->layout('layouts/layout') ?>

<br>
<div class="mx-auto p-5 shadow rounded" style="max-width: 400px">
   <form method="post" action="/account/register">
      <h2 class="text-center text-info">Register</h2>
      <div class="mb-3">
         <label for="InputName" class="form-label">Full name</label>
         <input type="text" class="form-control" id="InputName" name="Name" required>
      </div>
      <div class="mb-3">
         <label for="InputEmail" class="form-label">Email address</label>
         <input type="email" class="form-control" id="InputEmail" name="Email" required>
      </div>
      <div class="mb-3">
         <label for="InputPassword" class="form-label">Password</label>
         <input type="password" class="form-control" id="InputPassword" name="Password" pattern="^(?=.*?[A-Z])(?=.*?[0-9]).{8,}$" required>
      </div>
      <div class="d-grid gap-2">
         <button type="submit" class="btn btn-info text-white">Register</button>
      </div>
   </form>
</div>
